esphome:
  name: "esp8266-chime"
  # WICHTIG: baud_rate 0 setzen für ESP8266, da I2S DOUT auf GPIO3 (RX) liegt!
  # Andernfalls blockiert der Logger die Audioausgabe.
  # logger:
  #   baud_rate: 0
  includes:
    - ESP8266-Chime.h
  libraries:
    - "earlephilhower/ESP8266Audio"

esp8266:
  board: d1_mini

# Deaktiviere Logging über Seriell, da GPIO3 für I2S Audio benutzt wird
logger:
  baud_rate: 0

custom_component:
  - id: my_chime
    # Übergabe Pin 12 (GPIO12) für den Amp-Shutdown an den Konstruktor
    lambda: |-
      auto chime = new ESP8266Chime(12);
      return {chime};

api:
  services:
    - service: play_sound
      variables:
        sound_id: int
      then:
        - lambda: |-
            ((ESP8266Chime*)id(my_chime)[0])->play(sound_id);

    - service: stop_sound
      then:
        - lambda: |-
            ((ESP8266Chime*)id(my_chime)[0])->stop();

    - service: set_volume
      variables:
        volume: float
      then:
        - lambda: |-
            ((ESP8266Chime*)id(my_chime)[0])->set_volume(volume);

# Um WAV-Dateien in ein C-Array umzuwandeln, nutze z.B. xxd: `xxd -i audio.wav > audio.h`
