esphome:
  name: test-chime

esp8266:
  board: d1_mini

logger:
  baud_rate: 0

external_components:
  - source:
      type: local
      path: components

esp8266_chime:
  id: my_chime
  bclk: GPIO15
  ws: GPIO2
  dout: GPIO3
  i2s_format: LSBJ
  sd:
    number: GPIO12
    inverted: false
  language: en
  led:
    out: GPIO14
    frequenz:
      name: "LED Frequenz"
    duration:
      name: "LED Blinkdauer"
    activation:
      name: "LED Aktivieren"
